### ISSUE TITLE
translate_cmf_and_print

### ISSUE THREAD

**Issue by shedariia** [shedariia/morse#17]
Function not appeared.

**Comment by Tamir91** [comment]
Rebinding function was completed.
But now it print duplicated last **character** .

**Comment by shedariia** [comment]
void word_from_cmf_to_txt(String translate, String mcf_word, Morsetree * tree)
{
   ...
	while (*mcf_word_p)
	{
		if (*mcf_word_p != ' ') 
		{
			letter[i++] = *mcf_word_p;
			letter[i] = '\0';
		}
		mcf_word_p++;

		if (*mcf_word_p == ' ' && i > 0 && *(mcf_word_p - 1) == ' ' || *mcf_word_p == '\0') {
			i = 0;
			*translate_p = read_cmc(tree, **letter**);
			*translate_p++;
			*translate_p = '\0';
		}
	}
}
